### ISSUE TITLE
Feature#01-Mejora de la Clase Point

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#1]
Feature#1

Implementar la mejora de la Clase Point
Adjunto link de Wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-1-clase-point

**Comment by betocols** [comment]
Creado el método addTenToX() en la clase Point junto a su respectiva prueba.

**Comment by hejaloza** [comment]
@betocols , Buen Trabajo Alberto..
