### ISSUE TITLE
Feature#02-Mejora de la Clase User

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#2]
Feature#2

Implementar mejora de la Clase User
Adjunto link de Wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-2-clase-user

**Comment by fabricioflores** [comment]
Método para devolver el nombre en minúsculas creado.
Test unitario también agegado

**Comment by hejaloza** [comment]
Hola Fabricio, ya revise la Feature#2  y esta todo Correcto
Listo.!

**Comment by hejaloza** [comment]
@fabricioflores , Buen Trabajo Fabricio..
