### ISSUE TITLE
Feature#03-Mejora en la Clase DecimalCollection

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#3]
Feature#3

Implementar mejora de la Clase DecimalCollection
Adjunto link de Wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-3-clase-decimalcollection

**Comment by marianasalcedo** [comment]
Creado el método first con su respectiva prueba

**Comment by hejaloza** [comment]
@marianasalcedo , Estimada Mariana el metodo y su test esta correcto, pero me he dado cuenta que no esta hecho el merge con el commit para que la rama  feature#03 deje rastro en el historial. Puede revisar esa parte...?

**Comment by hejaloza** [comment]
@marianasalcedo , La implementación del método y su test  esta correcto, pero no se hizo el commit de la rama para que deje rastro del historial de la misma.

**Comment by marianasalcedo** [comment]
@hejaloza en efecto se hizo el merge con develop, solo que no force el commit al realizar el merge, disculpa
