### ISSUE TITLE
Feature#04-Implementar mejora1 en la Clase Fraction

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#4]
Feature#4

Implementar la primera mejora de la Clase Fraction
Adjunto link de Wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-41-clase-fraction

**Comment by betocols** [comment]
@hejaloza en la descripción de la ampliación indicas que debo devolver un valor entero. ¿Qué valor retorno en caso de que el resultado de la suma de numerador y denominador da un número impar? Si el resultado es 3.5, ¿devuelvo 3 o devuelvo 4?

**Comment by hejaloza** [comment]
@betocols  ok, puede hacer que devuelva el valor redondeado, por ejemplo si el resultado es 3.5 devolver 4

**Comment by hejaloza** [comment]
@betocols , O si prefieres puedes devolver el resultado de la siguiente manera, por ejemplo si el resultado es 3.5 devolver 3.

Las dos maneras anteriormente explicadas son validas, implementa la que mejor te convenga. Suerte!

**Comment by betocols** [comment]
Creado método numPlusDen en la clase Fraction con su respectiva prueba unitaria
