### ISSUE TITLE
Feature#05-Implementar mejora 2 en la Clase Fraction

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#5]
Feature#5

Implementar la segunda mejora de la Clase Fraction
Adjunto el link de Wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-42-clase-fraction

**Comment by fabricioflores** [comment]
Método para agregar en 1 el denominador y devolverlo agregado
También se agregaron los test unitarios

**Comment by hejaloza** [comment]
Hola Fabricio, ya revise la Feature#5  y esta todo Correcto
Listo.!

**Comment by hejaloza** [comment]
@fabricioflores , Buen trabajo Fabricio..
