### ISSUE TITLE
Feature#06-Implementar mejora3 de la Clase Fraction

### ISSUE THREAD

**Issue by hejaloza** [hejaloza/IWVG.SwC.HectorLozano#6]
Feature#6

Implementar la tercera mejora de la Clase Fraction
Adjunto link de wiki:

https://github.com/hejaloza/IWVG.SwC.HectorLozano/wiki/Proyecto:-Software-Colaborativo#mejora-43-clase-fraction

**Comment by marianasalcedo** [comment]
Agregado el metodo timesFractionElements con su prueba testTimesFractionElements

**Comment by hejaloza** [comment]
@marianasalcedo , Estimada Mariana el metodo y su test esta correcto, pero me he dado cuenta que no esta hecho el merge con el commit para que la rama  feature#06 deje rastro en el historial. Puede revisar esa parte...?

**Comment by hejaloza** [comment]
@marianasalcedo , La implementación del método y su test  esta correcto, pero no se hizo el commit de la rama para que deje rastro del historial de la misma.

**Comment by marianasalcedo** [comment]
@hejaloza en efecto se hizo el merge con develop, solo que no force el commit al realizar el merge, disculpa.
